### ISSUE TITLE
Spell check: "seperator" should be "separator"

### ISSUE THREAD

**Issue by xpe** [calebmer/inflections#3]
The word is commonly misspelled, FWIW.

**Comment by xpe** [comment]
I found some examples in documentation online; e.g.:

http://calebmer.com/inflections/src/inflections/case.rs.html#1-622

Here is a link to check all your repos:

https://github.com/search?l=&q=seperator+user%3Acalebmer&ref=advsearch&type=Code&utf8=✓

**Comment by japaric** [comment]
I think all the typos, in this repo, were already fixed in 1.1.0. The documentation link in the README has been [updated](https://docs.rs/inflections) though.

Thanks for the report, @xpe.
